#!/usr/bin/env ruby
#^syntax detection

site 'https://supermarket.chef.io/api/v1'

cookbook 'application_ruby'
cookbook 'apt'
cookbook 'user'
cookbook 'ruby_build'
cookbook 'git'
cookbook 'chef-client'
cookbook 'runit'
